/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilidade.Conexao;

/**
 *
 * @author kikog
 */
public class TelaSaida extends javax.swing.JFrame {

    String estacionamento;
    Conexao con;

    public TelaSaida(String estacionamento) {
        initComponents();
        this.estacionamento = estacionamento;
        jLTitulo.setText("Saída de Veículos - " + this.estacionamento);
        conectaBanco();
    }

    private void conectaBanco() {
        try {
            con = new Conexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jLId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estacionamento Universitário - Saída de Veículos");

        jLTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLTitulo.setText("Saída de Veículos - Estacionamento X");

        jBConfirmar.setText("Confirmar Saída");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jLId.setText("Identificador do Usuário:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTFId)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        if (!jTFId.getText().equals("")) {
            try {
                int id_usuario = Integer.parseInt(jTFId.getText());
                ResultSet rs = con.select("SELECT COUNT(*) AS count, v.placa_veiculo FROM estacionada e JOIN estacionamento es ON e.id_estacionamento=es.id_estacionamento JOIN veiculo v ON e.placa_veiculo=v.placa_veiculo JOIN usuario u ON u.id_usuario=v.id_usuario WHERE u.id_usuario=" + id_usuario + " AND e.datahora_saida_estacionada IS NULL AND es.nome_estacionamento='" + estacionamento + "'");
                rs.first();
                if (rs.getInt("count") > 1) {
                    JOptionPane.showMessageDialog(this, "Há mais de um veículo do mesmo usuário neste estacionamento", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
                    jTFId.setText("");
                    jTFId.requestFocus();
                    return;
                } else if (rs.getInt("count") == 0) {
                    JOptionPane.showMessageDialog(this, "Não há veículos deste usuário neste estacionamento", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
                    jTFId.setText("");
                    jTFId.requestFocus();
                    return;
                }
                String placa_veiculo = rs.getString("v.placa_veiculo");
                String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
                con.insert("UPDATE estacionada SET datahora_saida_estacionada='" + timeStamp + "' WHERE placa_veiculo='" + placa_veiculo + "' AND datahora_saida_estacionada IS NULL");
                JOptionPane.showMessageDialog(this, placa_veiculo + " saiu do estacionamento", "Estacionamento Universitário", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Identificador inválido", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
            }
            jTFId.setText("");
            jTFId.requestFocus();
        } else {
            jTFId.requestFocus();
        }
    }//GEN-LAST:event_jBConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFId;
    // End of variables declaration//GEN-END:variables
}
