/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import classe.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import utilidade.Conexao;

/**
 *
 * @author Seven
 */
public class TelaGerirUsuario extends javax.swing.JFrame {

    Conexao con;
    LinkedList<Usuario> usuarios = new LinkedList<>();

    public TelaGerirUsuario() {
        initComponents();
        ajeitaTabela();
        conectaBanco();
    }

    private void adicionaDadosTabela() {
        DefaultTableModel model = (DefaultTableModel) jTUsuarios.getModel();
        model.setRowCount(0);
        for (int x = 0; x < usuarios.size(); x++) {
            if (usuarios.get(x).getNome_usuario().toLowerCase().contains(jTFBusca.getText().toLowerCase())) {
                model.addRow(new Object[]{usuarios.get(x).getId_usuario(), usuarios.get(x).getNome_cargo(), usuarios.get(x).getNome_usuario()});
            }
        }
    }

    private void conectaBanco() {
        try {
            con = new Conexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ajeitaTabela() {
        setaTamanhoColuna(0, 80);
        setaTamanhoColuna(1, 150);
        setaTamanhoColuna(2, 350);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.LEFT);
        jTUsuarios.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }

    private void setaTamanhoColuna(int coluna, int tamanho) {
        jTUsuarios.getColumnModel().getColumn(coluna).setMinWidth(tamanho);
        jTUsuarios.getColumnModel().getColumn(coluna).setMaxWidth(tamanho);
        jTUsuarios.getColumnModel().getColumn(coluna).setPreferredWidth(tamanho);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jBAdicionar = new javax.swing.JButton();
        jLBuscar = new javax.swing.JLabel();
        jTFBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estacionamento Universitário - Usuários");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Cargo", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        jBAdicionar.setText("Adicionar Usuário");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jLBuscar.setText("Buscar usuário:");

        jTFBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBuscaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFBusca)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        new TelaManipularUsuario(null).setVisible(true);
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        usuarios.clear();
        try {
            ResultSet rs = con.select("SELECT * FROM usuario JOIN cargo ON usuario.id_cargo=cargo.id_cargo ORDER BY usuario.id_usuario");
            while (rs.next()) {
                if (!rs.getString("usuario.nome_usuario").equals("Visitante")) {
                    usuarios.add(new Usuario(rs.getInt("usuario.id_usuario"), rs.getInt("usuario.id_cargo"), rs.getString("usuario.nome_usuario"), rs.getString("cargo.nome_cargo")));
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
        adicionaDadosTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        int resposta = JOptionPane.showOptionDialog(this, "O que você deseja fazer com o usuário selecionado?", "Estacionamento Universitário", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Alterar", "Remover", "Visualizar Veículos"}, null);
        try {
            int id_usuario = (int) jTUsuarios.getModel().getValueAt(jTUsuarios.getSelectedRow(), 0);
            switch (resposta) {
                case 0:
                    new TelaManipularUsuario(usuarios.get(jTUsuarios.getSelectedRow())).setVisible(true);
                    break;
                case 1:
                    int respostaDelete = JOptionPane.showOptionDialog(this, "Você realmente deseja deletar o usuário selecionado?", "Estacionamento Universitário", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sim", "Cancelar"}, null);
                    switch (respostaDelete) {
                        case 0:
                            con.insert("DELETE FROM usuario WHERE id_usuario=" + id_usuario);
                            break;
                        case 1:
                            break;
                    }
                    break;
                case 2:
                    new TelaVeiculos(usuarios.get(jTUsuarios.getSelectedRow())).setVisible(true);
                    break;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Não é possível remover o usuário selecionado pois há veículos do mesmo cadastrado. Por favor, remova antes seus veículos.", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jTFBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscaKeyReleased
        // TODO add your handling code here:
        adicionaDadosTabela();
    }//GEN-LAST:event_jTFBuscaKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JLabel jLBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBusca;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
