/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import classe.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilidade.Conexao;

/**
 *
 * @author kikog
 */
public class TelaVeiculos extends javax.swing.JFrame {

    Conexao con;
    Usuario usuario;
    
    public TelaVeiculos(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        jLConteudoNome.setText(this.usuario.getNome_usuario());
        conectaBanco();
    }
    
    private void conectaBanco(){
        try {
            con = new Conexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: "+ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private String perguntaPlaca(boolean alteracao){
        String tmp;
        if (alteracao){
            tmp = " nova";
        } else {
            tmp = "";
        }
        while (true){
            String placa;
            placa = JOptionPane.showInputDialog(this, "Informe a"+tmp+" placa do veículo, no padrão XXX-0000", "Estacionamento Universitário - Veículos", JOptionPane.QUESTION_MESSAGE);
            if (placa==null){
                return null;
            }
            placa = placa.toUpperCase();
            if (validaPlaca(placa)){
                return placa;
            }
        }
    }
    
    private boolean validaPlaca(String placa){
        if (placa.length()==8){
            for (int x=0;x<placa.length();x++){
                if (x>=0 && x<=2){
                    if (placa.charAt(x)<'A' || placa.charAt(x)>'Z'){
                        return false;
                    }
                } else if (x==3){
                    if (placa.charAt(x) != '-'){
                        return false;
                    }
                } else if (x>3){
                    if (placa.charAt(x)<'0' || placa.charAt(x)>'9'){
                        return false;
                    }
                }
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();
        jBAdicionar = new javax.swing.JButton();
        jLTituloNome = new javax.swing.JLabel();
        jLConteudoNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estacionamento Universitário - Veículos");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa do Veículo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTVeiculos);

        jBAdicionar.setText("Adicionar Veículo");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jLTituloNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLTituloNome.setText("Nome:");

        jLConteudoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAdicionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLTituloNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLConteudoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLTituloNome, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLConteudoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVeiculosMouseClicked
        int resposta = JOptionPane.showOptionDialog(this, "O que você deseja fazer com o veículo selecionado?", "Estacionamento Universitário", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Alterar", "Remover"}, null);
        try {
            String placa_veiculo = (String) jTVeiculos.getValueAt(jTVeiculos.getSelectedRow(), 0);
            switch (resposta){
                case 0:
                    String placa_nova = perguntaPlaca(true);
                    con.insert("UPDATE veiculo SET placa_veiculo='"+placa_nova+"' WHERE placa_veiculo='"+placa_veiculo+"'");
                    break;
                case 1:
                    con.insert("DELETE FROM veiculo WHERE placa_veiculo='"+placa_veiculo+"'");
                    break;
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "SQLException: "+ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTVeiculosMouseClicked

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        String placa = perguntaPlaca(false);
        if (placa != null){
            try {
                con.insert("INSERT INTO veiculo (placa_veiculo, id_usuario) VALUES ('"+placa+"', "+usuario.getId_usuario()+")");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Essa placa já está cadastrada", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        DefaultTableModel model = (DefaultTableModel) jTVeiculos.getModel();
        model.setRowCount(0);
        try {
            ResultSet rs = con.select("SELECT * FROM veiculo WHERE id_usuario="+usuario.getId_usuario());
            while (rs.next()){
                model.addRow(new Object[]{rs.getString("placa_veiculo")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: "+ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JLabel jLConteudoNome;
    private javax.swing.JLabel jLTituloNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTVeiculos;
    // End of variables declaration//GEN-END:variables
}
