/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import utilidade.Conexao;

/**
 *
 * @author kikog
 */
public class TelaEntrada extends javax.swing.JFrame {

    String estacionamento;
    Conexao con;

    public TelaEntrada(String estacionamento) {
        initComponents();
        this.estacionamento = estacionamento;
        jLTitulo.setText("Entrada de Veículos - " + this.estacionamento);
        conectaBanco();
    }

    private void conectaBanco() {
        try {
            con = new Conexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }

    private int getId_estacionamento() throws SQLException {
        ResultSet rs = con.select("SELECT id_estacionamento FROM estacionamento WHERE nome_estacionamento='" + this.estacionamento + "'");
        rs.first();
        return rs.getInt("id_estacionamento");
    }

    private boolean validaPlaca(String placa) {
        if (placa.length() == 8) {
            for (int x = 0; x < placa.length(); x++) {
                if (x >= 0 && x <= 2) {
                    if (placa.charAt(x) < 'A' || placa.charAt(x) > 'Z') {
                        return false;
                    }
                } else if (x == 3) {
                    if (placa.charAt(x) != '-') {
                        return false;
                    }
                } else if (x > 3) {
                    if (placa.charAt(x) < '0' || placa.charAt(x) > '9') {
                        return false;
                    }
                }
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jLId = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jBConfirmar = new javax.swing.JButton();
        jLPlaca = new javax.swing.JLabel();
        jFTFPlaca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estacionamento Universitário - Entrada de Veículos");

        jLTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLTitulo.setText("Entrada de Veículos - Estacionamento X");

        jLId.setText("Identificador do Usuário:");

        jBConfirmar.setText("Confirmar Entrada");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        jLPlaca.setText("Placa do Veículo");

        try {
            jFTFPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(jLTitulo)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addComponent(jTFId)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLId)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLPlaca)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jFTFPlaca))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        if (!jFTFPlaca.getText().equals("")) {
            if (!jTFId.getText().equals("")) {
                try {
                    String placa_veiculo = jFTFPlaca.getText().toUpperCase();
                    if (validaPlaca(placa_veiculo)) {
                        int id_usuario = Integer.parseInt(jTFId.getText());
                        ResultSet rs = con.select("SELECT COUNT(*) AS count FROM veiculo WHERE placa_veiculo='" + placa_veiculo + "' AND id_usuario='" + id_usuario + "'");
                        rs.first();
                        if (rs.getInt("count") == 0) {
                            JOptionPane.showMessageDialog(this, "Este veículo não é deste usuário", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
                            jTFId.setText("");
                            jTFId.requestFocus();
                            return;
                        }
                        rs = con.select("SELECT COUNT(*) AS count FROM estacionada e JOIN veiculo v ON e.placa_veiculo=v.placa_veiculo WHERE v.id_usuario=" + id_usuario + " AND e.datahora_saida_estacionada IS NULL");
                        rs.first();
                        if (rs.getInt("count") >= 1) {
                            JOptionPane.showMessageDialog(this, "Já há veículo(s) deste usuário nos estacionamentos da universidade", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
                            jTFId.setText("");
                            jFTFPlaca.setText("");
                            jFTFPlaca.requestFocus();
                            return;
                        }
                        int id_estacionamento = getId_estacionamento();
                        con.insert("INSERT INTO estacionada (placa_veiculo, id_estacionamento) VALUES ('" + placa_veiculo + "', " + id_estacionamento + ")");
                        JOptionPane.showMessageDialog(this, placa_veiculo + " entrou no estacionamento", "Estacionamento Universitário", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Placa inválida", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Identificador inválido", "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
                }
                jTFId.setText("");
                jFTFPlaca.setText("");
                jFTFPlaca.requestFocus();
            } else {
                jTFId.requestFocus();
            }
        } else {
            jFTFPlaca.requestFocus();
        }
    }//GEN-LAST:event_jBConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JFormattedTextField jFTFPlaca;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLPlaca;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFId;
    // End of variables declaration//GEN-END:variables
}
