/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilidade.Conexao;

/**
 *
 * @author kikog
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    Conexao con;

    public TelaPrincipal() {
        initComponents();
        conectaBanco();
    }

    private void conectaBanco() {
        try {
            con = new Conexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGerirUsuario = new javax.swing.JButton();
        jBEstacionar = new javax.swing.JButton();
        jBHistorico = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jBDadosOcupacao = new javax.swing.JButton();
        jBSobre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estacionamento Universitário - Início");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jBGerirUsuario.setText("Usuário");
        jBGerirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGerirUsuarioActionPerformed(evt);
            }
        });

        jBEstacionar.setText("Estacionamento");
        jBEstacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEstacionarActionPerformed(evt);
            }
        });

        jBHistorico.setText("Histórico");
        jBHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistoricoActionPerformed(evt);
            }
        });

        jLTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLTitulo.setText("Estacionamento Universitário");

        jBDadosOcupacao.setText("Dados de Ocupação");
        jBDadosOcupacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDadosOcupacaoActionPerformed(evt);
            }
        });

        jBSobre.setText("Sobre");
        jBSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSobreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLTitulo)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jBGerirUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEstacionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDadosOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLTitulo)
                .addGap(18, 18, 18)
                .addComponent(jBGerirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBEstacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBDadosOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBGerirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGerirUsuarioActionPerformed
        // TODO add your handling code here:
        new TelaGerirUsuario().setVisible(true);
    }//GEN-LAST:event_jBGerirUsuarioActionPerformed

    private void jBHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistoricoActionPerformed
        // TODO add your handling code here:
        new TelaHistorico().setVisible(true);
    }//GEN-LAST:event_jBHistoricoActionPerformed

    private void jBDadosOcupacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDadosOcupacaoActionPerformed
       new TelaDadosOcupacao().setVisible(true);
    }//GEN-LAST:event_jBDadosOcupacaoActionPerformed

    private void jBEstacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEstacionarActionPerformed
        try {
            int resposta = JOptionPane.showOptionDialog(this, "Você deseja controlar o estacionamento de entrada ou saída?", "Estacionamento Universitário", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Entrada", "Saída"}, null);
            if (resposta == -1) {
                return;
            }
            ResultSet rs = con.select("SELECT COUNT(*) AS count FROM estacionamento");
            rs.first();
            int qtde = rs.getInt("count");
            Object[] estacionamentos = new Object[qtde];
            rs = con.select("SELECT * FROM estacionamento");
            int x=0;
            while (rs.next()){
                estacionamentos[x] = rs.getString("nome_estacionamento");
                x++;
            }
            String estacionamento = (String) JOptionPane.showInputDialog(this, "Você deseja controlar o estacionamento de entrada ou saída?", "Estacionamento Universitário", JOptionPane.PLAIN_MESSAGE, null, estacionamentos, null);
            if (estacionamento == null) {
                return;
            }
            switch (resposta) {
                case 0:
                    new TelaEntrada(estacionamento).setVisible(true);
                    break;
                case 1:
                    new TelaSaida(estacionamento).setVisible(true);
                    break;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBEstacionarActionPerformed

    private void jBSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSobreActionPerformed
        // TODO add your handling code here:
        new TelaSobre().setVisible(true);
    }//GEN-LAST:event_jBSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                boolean txtExiste = new File("dados.txt").exists();
                if (txtExiste==true){
                    new TelaPrincipal().setVisible(true);
                } else {
                    new TelaValidaDadosBanco().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDadosOcupacao;
    private javax.swing.JButton jBEstacionar;
    private javax.swing.JButton jBGerirUsuario;
    private javax.swing.JButton jBHistorico;
    private javax.swing.JButton jBSobre;
    private javax.swing.JLabel jLTitulo;
    // End of variables declaration//GEN-END:variables
}
