/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import classe.Estacionada;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import utilidade.Conexao;

/**
 *
 * @author kikog
 */
public class TelaHistorico extends javax.swing.JFrame {

    Conexao con;
    LinkedList<Estacionada> estacionadas = new LinkedList<>();

    public TelaHistorico() {
        initComponents();
        conectaBanco();
        ajeitaTabela();
    }

    private void ajeitaTabela() {
        setaTamanhoColuna(0, 70);
        setaTamanhoColuna(1, 120);
        setaTamanhoColuna(2, 200);
        setaTamanhoColuna(3, 160);
        setaTamanhoColuna(4, 160);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.LEFT);
        jTHistorico.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);
    }

    private void setaTamanhoColuna(int coluna, int tamanho) {
        jTHistorico.getColumnModel().getColumn(coluna).setMinWidth(tamanho);
        jTHistorico.getColumnModel().getColumn(coluna).setMaxWidth(tamanho);
        jTHistorico.getColumnModel().getColumn(coluna).setPreferredWidth(tamanho);
    }

    private void conectaBanco() {
        try {
            con = new Conexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void adicionaDadosTabela() {
        DefaultTableModel model = (DefaultTableModel) jTHistorico.getModel();
        model.setRowCount(0);
        for (int x = 0; x < estacionadas.size(); x++) {
            if (estacionadas.get(x).getPlaca_veiculo().toLowerCase().contains(jTFPlaca.getText().toLowerCase())) {
                model.addRow(new Object[]{estacionadas.get(x).getPlaca_veiculo(), estacionadas.get(x).getNome_usuario(), estacionadas.get(x).getNome_estacionamento(), estacionadas.get(x).getDatahora_entrada(), estacionadas.get(x).getDatahora_saida()});
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTHistorico = new javax.swing.JTable();
        jLBuscarPlaca = new javax.swing.JLabel();
        jTFPlaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estacionamento Universitário - Histórico");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Proprietário", "Estacionamento", "Entrada", "Saida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTHistorico);

        jLBuscarPlaca.setText("Buscar placa:");

        jTFPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFPlacaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBuscarPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBuscarPlaca)
                    .addComponent(jTFPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        estacionadas.clear();
        try {
            ResultSet rs = con.select("SELECT v.placa_veiculo, u.nome_usuario, es.nome_estacionamento, e.datahora_entrada_estacionada, e.datahora_saida_estacionada FROM estacionada e JOIN estacionamento es ON es.id_estacionamento=e.id_estacionamento JOIN veiculo v ON v.placa_veiculo=e.placa_veiculo JOIN usuario u ON u.id_usuario=v.id_usuario");
            while (rs.next()) {
                estacionadas.add(new Estacionada(rs.getString("v.placa_veiculo"), rs.getString("u.nome_usuario"), rs.getString("es.nome_estacionamento"), rs.getString("e.datahora_entrada_estacionada"), rs.getString("e.datahora_saida_estacionada")));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: " + ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
        adicionaDadosTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTFPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFPlacaKeyReleased
        adicionaDadosTabela();
    }//GEN-LAST:event_jTFPlacaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBuscarPlaca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFPlaca;
    private javax.swing.JTable jTHistorico;
    // End of variables declaration//GEN-END:variables
}
