/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import classe.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilidade.Conexao;

/**
 *
 * @author kikog
 */
public class TelaManipularUsuario extends javax.swing.JFrame {

    Usuario usuario;
    Conexao con;
    
    public TelaManipularUsuario(Usuario usuario) {
        initComponents();
        conectaBanco();
        this.usuario = usuario;
        populaComboBox();
        if (this.usuario != null){
            jTFNome.setText(this.usuario.getNome_usuario());
            jCBCargo.setSelectedIndex(this.usuario.getId_cargo()-1);
        }
    }

    private void populaComboBox(){
        try {
            ResultSet rs = con.select("SELECT * FROM cargo ORDER BY id_cargo");
            while (rs.next()){
                String cargo = rs.getString("nome_cargo");
                if (!cargo.equals("Visitante")){
                    jCBCargo.addItem(cargo);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: "+ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void conectaBanco(){
        try {
            con = new Conexao();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQLException: "+ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNome = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLCargo = new javax.swing.JLabel();
        jCBCargo = new javax.swing.JComboBox<>();
        jBConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estacionamento Universitário - Manipular Usuário");

        jLNome.setText("Nome:");

        jLCargo.setText("Cargo:");

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNome)
                    .addComponent(jCBCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNome)
                            .addComponent(jLCargo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        if (!jTFNome.getText().equals("")){
            int cargo = jCBCargo.getSelectedIndex()+1;
            try {
                String acao;
                if (this.usuario == null){
                    con.insert("INSERT INTO usuario (id_cargo, nome_usuario) VALUES ("+cargo+", '"+jTFNome.getText()+"')");
                    acao = " inserido";
                } else {
                    con.insert("UPDATE usuario SET id_cargo="+cargo+", nome_usuario='"+jTFNome.getText()+"' WHERE id_usuario="+this.usuario.getId_usuario());
                    acao = " alterado";
                }
                JOptionPane.showMessageDialog(this, jCBCargo.getSelectedItem().toString()+acao+" com sucesso", "Estacionamento Universitário", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "SQLException: "+ex, "Estacionamento Universitário", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jBConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JComboBox<String> jCBCargo;
    private javax.swing.JLabel jLCargo;
    private javax.swing.JLabel jLNome;
    private javax.swing.JTextField jTFNome;
    // End of variables declaration//GEN-END:variables
}
