<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
      Generated by Composer.
      http://www.di.uminho.pt/~jcr/PROJS/Composer/
      Copyright (C) 2003 José Carlos Ramalho
      Permission to use granted under GPL or MPL.

      History: 
      2003-10-15 Created jcr    
      --><xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
   <xsl:output method="xml" omit-xml-declaration="no" encoding="iso-8859-1" standalone="yes"
               indent="yes"/>
   <xsl:template match="/">
      <resultado>
         <xsl:element name="Entrada555">
            <xsl:apply-templates mode="P1Q0" select="document('agenda.xml')"/>
         </xsl:element>
         <xsl:element name="VersoNãoTemNome">
            <xsl:apply-templates mode="P2Q0" select="document('poema.xml')"/>
         </xsl:element>
      </resultado>
   </xsl:template>
   <xsl:template mode="P1Q0" match="//entrada[starts-with(telefone,'555')]">
      <xsl:copy-of select="."/>
   </xsl:template>
   <xsl:template match="text()" priority="-1" mode="P1Q0"/>
   <xsl:template mode="P2Q0" match="//verso[not(nome)]">
      <xsl:copy-of select="."/>
   </xsl:template>
   <xsl:template match="text()" priority="-1" mode="P2Q0"/>
   <xsl:template match="text()" priority="-1"/>
</xsl:stylesheet>